### ISSUE TITLE
Request for the paper

### ISSUE THREAD

**Issue by zchrissirhcz** [USTClj/Traffic_Sign_Recognition_Efficient_CNNs#1]
First, thanks for sharing the code.

I notice that this repo is for the paper "Real-Time Traffic Sign Recognition Based on Efficient CNNs in the Wild", however, I searched on google and baidu, did not find a paper with exactly same name.

If convinient, would you please provide this paper? My email is imzhuo@foxmail, I would appreciate if I can have a look at your paper. 

Thanks.

**Comment by USTClj** [comment]
HI, @zchrissirhcz , the paper is under review now.

**Comment by zchrissirhcz** [comment]
Got it, @USTClj. Looking forward to your paper's good news.
