### ISSUE TITLE
Merge sequential models

### ISSUE THREAD

**Issue by citlag** [USTClj/Traffic_Sign_Recognition_Efficient_CNNs#4]
Hello, I am tempting to run your model for Classification but I am having a lot of troubles to fix the issue with Merge.

I read that from keras 1 +, Merge was not included anymore to merge sequential models. Do you have your CNN definition compatible with recent versions of keras? I guessed you used keras 0.3.3 or earlier but I cannot make jupyter notebook run with other versions.

If you have other solutions for this issue will be appreciate it.

Thank you!

**Comment by USTClj** [comment]
Hi, sorry for the late reply. I original model was built using keras 1.2 API. You can try to downgrade  the keras only while remain the version of you tensorflow.
