### ISSUE TITLE
下载出问题

### ISSUE THREAD

**Issue by cuicuizhang1989** [USTClj/Traffic_Sign_Recognition_Efficient_CNNs#6]
你好，国内和国外的网都下载不下来，请问可以给一个百度网盘地址吗？

**Comment by USTClj** [comment]
您可以选择克隆代码部分，可能是测试样例图片太多。classier 的权值文件项目已给出云盘链接。detector 的一个可用的权值文件如下：
链接: https://pan.baidu.com/s/1Wnsxdcxx8oQ-2B4xhQ08ag 提取码: gnxe
