### ISSUE TITLE
CPU-Mode

### ISSUE THREAD

**Issue by langelesl** [USTClj/Traffic_Sign_Recognition_Efficient_CNNs#8]
Hello Jia. Thank you for sharing your wonderful codes. I noticed you've uploaded your weight and test_frcnn.py for testing in the detection part. Is it possible to test your code in CPU-Mode without CUDA? If positive, could you please share your tips about modifying your code? I will appreciate your help.

**Comment by USTClj** [comment]
You can just change 
`os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # use GTX 1080`
to 
`os.environ["CUDA_VISIBLE_DEVICES"] = " "  # use GTX 1080`
in
https://github.com/USTClj/Traffic_Sign_Recognition_Efficient_CNNs/blob/2998d56e45d625c1b35a31ff28467aaf092ec627/Detection/mobilenet_frcnn_detector/test_frcnn.py#L17

Our final  inner code is actually follows [Mask_RCNN](https://github.com/matterport/Mask_RCNN).

**Comment by langelesl** [comment]
@USTClj  Great, I will try it later. Thanks for your reply.
